apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      type: backend
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: container
          image: yunseull/backend:latest
      terminationGracePeriodSeconds: 3